version: '3.8'

services:
  db:
    image: postgres:latest  
    container_name: postgres-container  
    environment:
      POSTGRES_USER: yarolys
      POSTGRES_PASSWORD: Vlad1000000
      POSTGRES_DB: database.db
    volumes:
      - postgres_data:/var/lib/postgresql/data  
    ports:
      - "5432:5432"  

volumes:
  postgres_data:
    driver: local